name: Install TOSCA CLI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-tosca-cli:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          $env:TOSCA_CLI_URL = "https://example.com/tosca-cli/windows/tosca-cli.exe"  # Replace with the actual TOSCA CLI URL
          $env:TOSCA_CLI_PATH = "C:\tools\tosca-cli"
          if (!(Test-Path -Path $env:TOSCA_CLI_PATH)) {
            New-Item -ItemType Directory -Force -Path $env:TOSCA_CLI_PATH
          }

      - name: Download TOSCA CLI
        run: |
          Invoke-WebRequest -Uri $env:TOSCA_CLI_URL -OutFile "$env:TOSCA_CLI_PATH\tosca-cli.exe"

      - name: Add TOSCA CLI to PATH
        shell: pwsh
        run: |
          $env:Path += ";$env:TOSCA_CLI_PATH"
          [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)
      
      - name: Verify TOSCA CLI installation
        run: tosca-cli --version
